---

- name: Ensure Metax database is present
  postgresql_db: name="{{ metax_db_name }}"
  become_user: postgres

- name: Ensure Metax database user exists and has access
  postgresql_user: db={{ metax_db_name }} name={{ metax_db_user }} password={{ metax_db_password_local_dev_env }} priv=ALL
  become_user: postgres

- name: Remove unnecessary privileges from user
  postgresql_user: name={{ metax_db_name }} role_attr_flags=NOSUPERUSER,NOCREATEDB
  become_user: postgres

- name: Remove unnecessary privileges from others
  postgresql_privs: db={{ metax_db_name }} role=PUBLIC type=database priv=ALL state=absent
  become_user: postgres
