- name: Copy app config to target VM
  copy: src=sec/vars/{{ deployment_environment_id }}.yml dest=/home/{{ django_user }}/app_config owner={{ django_user }} group=metax mode=0440

- name: Create folder {{ metax_app_base_path }}
  file: path={{ metax_app_base_path }} state=directory owner={{ django_user }} group=metax mode=0755

- name: Clone project repo from branch {{ project_repo_branch }} to {{ metax_app_base_path }}
  git: repo={{ project_repo }} dest={{ metax_app_base_path }} version={{ project_repo_branch }}
  become_user: "{{ django_user }}"
  ignore_errors: yes

- name: Install app python package requirements
  pip: requirements={{ metax_app_base_path }}/requirements.txt virtualenv={{ python_virtualenv_path }}
  become_user: "{{ django_user }}"

- name: Create directory for static files
  file: path={{ static_root }} state=directory owner={{ django_user }} group=metax

- name: Create django app logging directory
  file: path=/var/log/metax-api state=directory owner={{ django_user }} group=metax

- name: Create django app log file and ensure file permissions
  copy: content="" dest=/var/log/{{ project_name }}/metax_api.log force=no owner={{ django_user }} group=metax mode=0755

- name: Symlink pre-commit hook in .githooks/ to .git/hooks/
  shell: cd {{ metax_app_base_path }}/.git/hooks; ln -sfn ../../.githooks/pre-commit pre-commit
  when: deployment_environment_id == 'local_development'

- include_role: name=gunicorn
