---

- name: Add users to OS
  user: name={{ item }} groups=wheel,metax state=present createhome=yes
  with_items: "{{ os_users }}"

- name: Create .ssh folders to users' home folders in cloud environment
  file: path=/home/{{ item }}/.ssh owner={{ item }} mode=0700 state=directory
  with_items: "{{ os_users }}"
  when: deployment_environment_id != 'local_development'

- name: Add users' public keys to cloud environment
  copy: src=sec/public_keys/{{ item }}.pub dest=/home/{{ item }}/.ssh/authorized_keys owner={{ item }} mode=0700
  with_items: "{{ os_users }}"
  when: deployment_environment_id != 'local_development'
