# SPDX-FileCopyrightText: Copyright (c) 2018-2019 Ministry of Education and Culture, Finland
#
# SPDX-License-Identifier: GPL-3.0-or-later
---

- name: Install centos-release-scl software collections
  shell: yum -y install centos-release-scl warn=false
  when: deployment_environment_id ==  'local_development'

- name: APACHE | Install httpd24
  shell: yum -y install httpd24-httpd warn=false

- name: APACHE | Install mod_auth_openidc from centos standard repository. Installs also vanilla httpd
  shell: yum -y install mod_auth_openidc warn=false

- name: APACHE | Link mod_auth_openidc to custom httpd24 modules location
  file:
    src: '/etc/httpd/modules/mod_auth_openidc.so'
    dest: '/opt/rh/httpd24/root/etc/httpd/modules/mod_auth_openidc.so'
    state: link

- name: APACHE | Copy metax httpd24 conf file
  template: src=templates/metax_httpd.conf dest=/opt/rh/httpd24/root/etc/httpd/conf.d/metax_httpd.conf

- name: APACHE | Copy metax httpd24 modules file
  template: src=templates/00-metax_modules.conf dest=/opt/rh/httpd24/root/etc/httpd/conf.modules.d/00-metax_modules.conf

- name: APACHE | Disable httpd24 listening on port 80 by default
  lineinfile:
    dest: "/opt/rh/httpd24/root/etc/httpd/conf/httpd.conf"
    state: present
    regexp: '^#?\s?Listen 80'
    line: "# Listen 80"

- name: APACHE | Load custom list of httpd24 modules, instead of all default modules
  lineinfile:
    dest: "/opt/rh/httpd24/root/etc/httpd/conf/httpd.conf"
    state: present
    regexp: "Include conf.modules.d"
    line: "Include conf.modules.d/00-metax_modules.conf"

- name: APACHE | Only load custom metax.conf, not all confs from conf.d/
  lineinfile:
    dest: "/opt/rh/httpd24/root/etc/httpd/conf/httpd.conf"
    state: present
    regexp: "IncludeOptional conf.d"
    line: "IncludeOptional conf.d/metax_httpd.conf"

- name: Set vanilla httpd service to not auto-restart
  lineinfile:
    path: /usr/lib/systemd/system/httpd.service
    state: present
    line: 'Restart=no'

- name: Ensure vanilla httpd is stopped
  service: name=httpd enabled=no state=stopped

- name: APACHE | Restart httpd24
  service: name=httpd24-httpd enabled=yes state=restarted
