---

- name: Install centos-release-scl software collections
  yum: name=centos-release-scl
  when: deployment_environment_id ==  'local_development'

- name: APACHE | Install httpd
  yum: name=httpd24-httpd state=latest

- name: APACHE | Install mod_auth_openidc from centos standard repository
  yum: name=mod_auth_openidc state=latest

- name: APACHE | Link mod_auth_openidc to custom httpd modules location
  file:
    src: '/etc/httpd/modules/mod_auth_openidc.so'
    dest: '/opt/rh/httpd24/root/etc/httpd/modules/mod_auth_openidc.so'
    state: link

- name: APACHE | Copy metax httpd conf file
  template: src=templates/metax_httpd.conf dest=/opt/rh/httpd24/root/etc/httpd/conf.d/metax_httpd.conf

- name: APACHE | Copy metax httpd modules file
  template: src=templates/00-metax_modules.conf dest=/opt/rh/httpd24/root/etc/httpd/conf.modules.d/00-metax_modules.conf

- name: APACHE | Disable listening on port 80 by default
  lineinfile:
    dest: "/opt/rh/httpd24/root/etc/httpd/conf/httpd.conf"
    state: present
    regexp: "Listen 80"
    line: "# Listen 80"

- name: APACHE | Load custom list of httpd modules, instead of all default modules
  lineinfile:
    dest: "/opt/rh/httpd24/root/etc/httpd/conf/httpd.conf"
    state: present
    regexp: "Include conf.modules.d"
    line: "Include conf.modules.d/00-metax_modules.conf"

- name: APACHE | Only load custom metax.conf, not all confs from conf.d/
  lineinfile:
    dest: "/opt/rh/httpd24/root/etc/httpd/conf/httpd.conf"
    state: present
    regexp: "IncludeOptional conf.d"
    line: "IncludeOptional conf.d/metax_httpd.conf"

- name: APACHE | Restart httpd
  service: name=httpd24-httpd enabled=yes state=restarted
