# SPDX-FileCopyrightText: Copyright (c) 2018-2019 Ministry of Education and Culture, Finland
#
# SPDX-License-Identifier: GPL-3.0-or-later

- name: Install python virtualenv for docs
  include_role:
    name: python
  vars:
    owner_user: "{{ app_user }}"
    python_venv_path: "{{ python_virtualenv_path_docs }}"
  tags:
    - packages

- name: Copy docs requirements.txt to /tmp
  copy:
    src: files/requirements.txt
    dest: /tmp/requirements.txt
    owner: "{{ app_user }}"
    group: "metax"
    mode: "0400"
  tags:
    - packages

- name: Install docs python package requirements
  pip: requirements=/tmp/requirements.txt virtualenv={{ python_virtualenv_path_docs }}
  become_user: "{{ app_user }}"
  tags:
    - packages

- name: Delete docs requirements.txt from /tmp
  file:
    state: absent
    path: /tmp/requirements.txt
  tags:
    - packages

- name: Sphinx tasks
  include_tasks: sphinx.yml
  loop: "{{ api_versions_enabled }}"
  loop_control:
    loop_var: api_version
  tags:
    - sphinx

- name: Swagger tasks
  include_tasks: swagger.yml
  loop: "{{ api_versions_enabled }}"
  loop_control:
    loop_var: api_version
  tags:
    - swagger
