---

- name: Check if Rabbitmq has been installed
  stat: path=/etc/init.d/rabbitmq-server
  register: rabbitmq

- block:
    - name: Install Erlang package
      apt: pkg=erlang state=latest

    - name: Add RabbitMQ official apt repository
      apt_repository: repo='deb http://www.rabbitmq.com/debian/ testing main' state=present update_cache=yes

    - name: Add RabbitMQ public key to trusted key list
      apt_key: url="https://www.rabbitmq.com/rabbitmq-release-signing-key.asc" state=present

    - name: Install RabbitMQ server
      apt: pkg=rabbitmq-server state=latest update_cache=yes

    - name: Enable RabbitMQ management plugin (access it via <ip_address>:15672)
      rabbitmq_plugin: names=rabbitmq_management state=enabled

  when: rabbitmq.stat.exists == False

- name: Add metax virtual host for RabbitMQ
  rabbitmq_vhost:
    name: "{{ RABBITMQ.VHOST }}"
    state: present

- name: Add new admin user for RabbitMQ
  rabbitmq_user:
    user: "{{ rabbitmq_admin_user }}"
    password: "{{ rabbitmq_admin_password }}"
    tags: administrator,admin
    permissions:
      - vhost: /
        configure_priv: .*
        read_priv: .*
        write_priv: .*
      - vhost: "{{ RABBITMQ.VHOST }}"
        configure_priv: .*
        read_priv: .*
        write_priv: .*
    state: present

- name: Add metax-user for RabbitMQ
  rabbitmq_user:
    user: "{{ RABBITMQ.USER }}"
    password: "{{ RABBITMQ.PASSWORD }}"
    vhost: "{{ RABBITMQ.VHOST }}"
    configure_priv: .*
    write_priv: .*
    read_priv: .*
    state: present

- name: Add known consumer users for RabbitMQ
  rabbitmq_user:
    user: "{{ item.NAME }}"
    password: "{{ item.PASSWORD }}"
    vhost: "{{ item.VHOST }}"
    configure_priv: "{{ item.PERMISSIONS.CONF }}"
    write_priv: "{{ item.PERMISSIONS.WRITE }}"
    read_priv: "{{ item.PERMISSIONS.READ }}"
    state: present
  with_items:
    - "{{ RABBITMQ.CONSUMERS }}"

- name: Remove default admin user
  rabbitmq_user: user=guest state=absent

- name: Restart RabbitMQ
  service: name=rabbitmq-server state=restarted
