---

- name: Check if Rabbitmq has been installed
  stat: path=/usr/lib/rabbitmq/bin/rabbitmq-server
  register: rabbitmq_server

- block:
    - name: Install Erlang package
      yum: name=erlang state=latest

    - name: Install RabbitMQ server
      yum: name=rabbitmq-server state=present

    - name: Enable RabbitMQ management plugin (access it via <ip_address>:15672)
      rabbitmq_plugin: names=rabbitmq_management state=enabled

    - name: Restart RabbitMQ server
      service: name=rabbitmq-server enabled=yes state=restarted

  when: rabbitmq_server.stat.exists == False

- name: Enable RabbitMQ disk_free_limit configuration
  lineinfile:
    dest: "/etc/rabbitmq/rabbitmq.config"
    state: present
    regexp: "^.*\\{disk_free_limit, \\{mem_relative"
    line: "{disk_free_limit, {mem_relative, 1.5}}"

- name: Setup .erlang.cookie
  copy:
    dest: /var/lib/rabbitmq/.erlang.cookie
    content: "{{ rabbitmq.erlang_cookie }}"

- name: Restart RabbitMQ
  service: name=rabbitmq-server state=restarted

- name: Add main virtual host for RabbitMQ
  rabbitmq_vhost:
    name: "{{ rabbitmq.vhost }}"
    state: present

- name: Add new admin user for RabbitMQ
  rabbitmq_user:
    user: "{{ rabbitmq.admin_user }}"
    password: "{{ rabbitmq.admin_password }}"
    tags: administrator,admin
    permissions:
      - vhost: /
        configure_priv: .*
        read_priv: .*
        write_priv: .*
      - vhost: "{{ rabbitmq.vhost }}"
        configure_priv: .*
        read_priv: .*
        write_priv: .*
    state: present

- name: Add metax-user for RabbitMQ
  rabbitmq_user:
    user: "{{ rabbitmq.user }}"
    password: "{{ rabbitmq.password }}"
    vhost: "{{ rabbitmq.vhost }}"
    configure_priv: .*
    write_priv: .*
    read_priv: .*
    state: present

- name: Add known consumer users for RabbitMQ
  rabbitmq_user:
    user: "{{ item.name }}"
    password: "{{ item.password }}"
    vhost: "{{ rabbitmq.vhost }}"
    configure_priv: "{{ item.permissions.conf }}"
    write_priv: "{{ item.permissions.write }}"
    read_priv: "{{ item.permissions.read }}"
    state: present
  with_items:
    - "{{ rabbitmq_consumers }}"

- name: Remove default admin user
  rabbitmq_user: user=guest state=absent
