# SPDX-FileCopyrightText: Copyright (c) 2018-2019 Ministry of Education and Culture, Finland
#
# SPDX-License-Identifier: GPL-3.0-or-later
---

  - name: Create database backup directory
    file: path={{ metax_db_backup_path }} state=directory owner=postgres group=postgres mode=0760 recurse=yes

  - name: Copy backup script in place
    template: src=templates/db_backup.sh dest={{ db_backup_dir_base_path }} owner=postgres group=postgres mode=0770

  - name: Create cronjob for running backup script
    cron:
      name: "Backup metax_{{ deployment_environment_id }} database and clean database backups and archives"
      minute: "30"
      hour: "2"
      job: "{{ db_backup_dir_base_path }}/db_backup.sh metax_{{ deployment_environment_id }} pg96 5432 {{ metax_db_archive_path }} {{ metax_db_backup_path }} > /dev/null 2>&1"
      state: present
      user: postgres
