---

- block:
    - name: Place database name {{ metax_database.name }} into target VM env vars
      lineinfile:
        dest: /etc/environment
        state: present
        line: 'METAX_DATABASE_NAME="{{ metax_database.name }}"'

    - name: Place database user {{ metax_database.user }} into target VM env vars
      lineinfile:
        dest: /etc/environment
        state: present
        line: 'METAX_DATABASE_USER="{{ metax_database.user }}"'

  when: deployment_environment_id in ['local_development', 'test', 'stable', 'staging']

- name: Install Postgresql repository
  yum_repository:
    name: postgresql
    description: Postresql
    baseurl: https://download.postgresql.org/pub/repos/yum/9.6/redhat/rhel-7.3-x86_64/
    gpgcheck: no
    state: present
  when: deployment_environment_id ==  'local_development'

- name: Install PostgreSQL 9 and python psycopg2
  yum:
    state: present
    name:
      - postgresql96
      - postgresql96-server
      - postgresql96-contrib
      - python-psycopg2

- name: Create/ensure data directory {{ data_dir_base_path }}
  file: path={{ data_dir_base_path }} state=directory owner={{ app_user }} group=metax mode=0755

- name: Create database data directory {{ metax_db_data_path }}
  file: path={{ metax_db_data_path }} state=directory owner=postgres group=postgres mode=700

- name: Initialize Postgres database to {{ metax_db_data_path }}
  command: /usr/pgsql-9.6/bin/pg_ctl initdb -D {{ metax_db_data_path }} creates={{ metax_db_data_path }}/postgresql.conf
  become_user: postgres

- block:
    - name: Copy bash aliases to postgres user home dir
      template: src=templates/postgres_bash_aliases dest=/var/lib/pgsql/.bash_aliases owner=postgres group=postgres

    - name: Touch postgres .bash_profile
      file: path=/var/lib/pgsql/.bash_profile owner=postgres group=postgres state=touch

    - name: Add printing of bash aliases to postgres profile
      lineinfile:
        dest: "/var/lib/pgsql/.bash_profile"
        state: present
        line: "{{ item }}"
      with_items:
        - "source .bash_aliases"
        - "aliases"

  when: deployment_environment_id in ['local_development', 'test', 'stable']

- name: Shutdown Postgresql
  systemd: name=postgresql-9.6 enabled=yes state=stopped

- name: Create custom Postgres service file that refers to the original one and set correct PGDATA location
  copy:
    dest: /etc/systemd/system/postgresql-9.6.service
    content: |
      .include /lib/systemd/system/postgresql-9.6.service
      [Service]
      Environment=PGDATA={{ metax_db_data_path }}

- name: Systemctl daemon-reload
  shell: "systemctl daemon-reload"

- include_role: name=pg_hba_conf

- name: Change Postgres configuration listen_address to all
  lineinfile:
    dest: "{{ metax_db_data_path }}/postgresql.conf"
    state: present
    regexp: "listen_addresses ="
    line: "listen_addresses = '*'"

- name: Change Postgres configuration log_timezone to Finnish locale
  lineinfile:
    dest: "{{ metax_db_data_path }}/postgresql.conf"
    state: present
    regexp: "log_timezone ="
    line: "log_timezone = 'Europe/Helsinki'"

- name: Change Postgres configuration default_transaction_isolation to Django recommended value
  lineinfile:
    dest: "{{ metax_db_data_path }}/postgresql.conf"
    state: present
    regexp: "default_transaction_isolation ="
    line: "default_transaction_isolation = 'read committed'"

- name: Change Postgres configuration timezone to Finnish locale
  lineinfile:
    dest: "{{ metax_db_data_path }}/postgresql.conf"
    state: present
    regexp: "timezone ="
    line: "timezone = 'Europe/Helsinki'"

- name: Change Postgres configuration client_encoding UTF8
  lineinfile:
    dest: "{{ metax_db_data_path }}/postgresql.conf"
    state: present
    regexp: "client_encoding ="
    line: "client_encoding = 'UTF8'"

- name: Change Postgres configuration lc_messages to Finnish locale UTF8
  lineinfile:
    dest: "{{ metax_db_data_path }}/postgresql.conf"
    state: present
    regexp: "lc_messages ="
    line: "lc_messages = 'en_US.UTF-8'"

- name: Change Postgres configuration lc_monetary to Finnish locale UTF8
  lineinfile:
    dest: "{{ metax_db_data_path }}/postgresql.conf"
    state: present
    regexp: "lc_monetary ="
    line: "lc_monetary = 'fi_FI.UTF-8'"

- name: Change Postgres configuration lc_numeric to Finnish locale UTF8
  lineinfile:
    dest: "{{ metax_db_data_path }}/postgresql.conf"
    state: present
    regexp: "lc_numeric ="
    line: "lc_numeric = 'fi_FI.UTF-8'"

- name: Change Postgres configuration lc_time to Finnish locale UTF8
  lineinfile:
    dest: "{{ metax_db_data_path }}/postgresql.conf"
    state: present
    regexp: "lc_time ="
    line: "lc_time = 'fi_FI.UTF-8'"

- name: Change Postgres configuration default_text_search_config to Finnish
  lineinfile:
    dest: "{{ metax_db_data_path }}/postgresql.conf"
    state: present
    regexp: "default_text_search_config ="
    line: "default_text_search_config = 'pg_catalog.finnish'"

- name: Optimize Postgres configuration shared_buffers
  lineinfile:
    dest: "{{ metax_db_data_path }}/postgresql.conf"
    state: present
    regexp: "shared_buffers ="
    line: "shared_buffers = '{{ (ansible_memtotal_mb*0.25) | int }}MB'"

- name: Optimize Postgres configuration effective_cache_size
  lineinfile:
    dest: "{{ metax_db_data_path }}/postgresql.conf"
    state: present
    regexp: "effective_cache_size ="
    line: "effective_cache_size = '{{ (ansible_memtotal_mb*0.75) | int }}MB'"

- name: Change Postgres configuration wal_level to replica
  lineinfile:
    dest: "{{ metax_db_data_path }}/postgresql.conf"
    state: present
    regexp: "^#?wal_level ="
    line: "wal_level = replica"

- name: Change Postgres configuration max_wal_senders to 1
  lineinfile:
    dest: "{{ metax_db_data_path }}/postgresql.conf"
    state: present
    regexp: "^#?max_wal_senders ="
    line: "max_wal_senders = 1"

- name: Change Postgres configuration archive_mode to on
  lineinfile:
    dest: "{{ metax_db_data_path }}/postgresql.conf"
    state: present
    regexp: "^#?archive_mode ="
    line: "archive_mode = on"

- name: Change Postgres configuration archive_command
  lineinfile:
    dest: "{{ metax_db_data_path }}/postgresql.conf"
    state: present
    regexp: "^#?archive_command ="
    line: "archive_command = 'test ! -f {{ metax_db_archive_path }}/%f && cp %p {{ metax_db_archive_path }}/%f && chmod 660 {{ metax_db_archive_path }}/%f'"

- name: Create wal archive directory
  file: path={{ metax_db_archive_path }} state=directory owner=postgres group=postgres mode=0760 recurse=yes

- name: Restart Postgresql
  systemd: name=postgresql-9.6 state=restarted daemon_reload=yes

- block:
    - name: Ensure Metax database user exists
      postgresql_user: name={{ metax_database.user }} password={{ metax_database.password }} state=present role_attr_flags=CREATEDB

    - name: Ensure Metax database is present
      postgresql_db: template=template0 db={{ metax_database.name }} state=present owner={{ metax_database.user }} encoding=UTF-8 lc_collate=fi_FI.UTF-8 lc_ctype=fi_FI.UTF-8

    - name: Remove unnecessary privileges from others
      postgresql_privs: db={{ metax_database.name }} role=PUBLIC type=database priv=ALL state=absent

  become_user: postgres
