---

- name: Install Postgresql repository
  yum_repository:
    name: postgresql
    description: Postresql
    baseurl: https://download.postgresql.org/pub/repos/yum/9.6/redhat/rhel-7.3-x86_64/
    gpgcheck: no
    state: present

- name: Install PostgreSQL 9 and python psycopg2
  yum: name={{ item }} state=present
  with_items:
    - postgresql96
    - postgresql96-server
    - postgresql96-devel
    - postgresql96-libs
    - python-psycopg2

- name: Create Postgres directories
  file: path={{ item }} state=directory owner=postgres group=postgres mode=700
  with_items:
    - "{{ metax_db_data_path }}"

- name: Initialize Postgres database cluster
  command: /usr/pgsql-9.6/bin/pg_ctl initdb -D {{ metax_db_data_path }} creates={{ metax_db_data_path }}/postgresql.conf
  become_user: postgres

- name: Copy Postgres configuration
  copy: src=pg_hba.conf dest={{ metax_db_data_path }}/pg_hba.conf owner=postgres group=postgres

- name: Install metaxdb service
  copy:
    dest: /etc/systemd/system/metaxdb.service
    content: |
      .include /lib/systemd/system/postgresql-9.6.service
      [Service]
      Environment=PGDATA={{ metax_db_data_path }}

- name: Install PostGIS
  yum: name=postgis2_96 state=present

- name: Enable metaxdb service
  systemd:
    name: metaxdb
    state: started
    enabled: yes
    daemon_reload: yes
