---

  - include_role:
      name: ansible-elasticsearch
    vars:
      es_instance_name: "{{ elasticsearch_instance.node_name }}"
      es_version: "5.5.1"
      es_config: {
        node.name: "{{ elasticsearch_instance.node_name }}",
        cluster.name: "{{ elasticsearch.cluster_name }}",
        node.data: "{{ elasticsearch_instance.is_data_node }}",
        node.master: "{{ elasticsearch_instance.is_master_node }}",
        http.cors.enabled : true,
        http.cors.allow-origin : "{{ elasticsearch_instance.allow_origin }}",
        http.cors.allow-methods : "OPTIONS, HEAD, GET, POST, PUT, DELETE",
        http.cors.allow-headers : "X-Requested-With,X-Auth-Token,Content-Type, Content-Length",
        network.host: [_local_, _site_]
      }

  - name: Pause for 30 seconds to allow elasticearch to respond
    pause: seconds=30

  - name: Copy reference and organization data indexing script
    copy: src=metax-refdata-indexer/ dest=/srv/refdata_indexer owner={{ django_user}} group=metax mode=740

  - name: Install indexing script dependencies
    pip: requirements=/srv/refdata_indexer/requirements.txt virtualenv={{ python_virtualenv_path }}
    become_user: "{{ django_user }}"

  - name: Index reference and organization data
    shell: cd /srv/refdata_indexer;./reindex_all.sh
    become_user: "{{ django_user }}"

  - name: Create cronjob for running reindexing script
    cron:
      name: "Reindex reference and organization data"
      minute: "00"
      hour: "3"
      job: "/srv/refdata_indexer/reindex_all.sh > /dev/null 2>&1"
      state: present
      user: "{{ django_user }}"
