# SPDX-FileCopyrightText: Copyright (c) 2018-2019 Ministry of Education and Culture, Finland
#
# SPDX-License-Identifier: GPL-3.0-or-later
---

  - include_role:
      name: ansible-elasticsearch
    vars:
      es_instance_name: "{{ elasticsearch_instance.node_name }}"
      es_heap_size: "{{ elasticsearch_instance.heap_size }}"
      es_version: "5.6.11"
      es_major_version: "5.x"
      es_version_lock: true
      es_xpack_features: []
      es_config: {
        node.name: "{{ elasticsearch_instance.node_name }}",
        cluster.name: "{{ elasticsearch_instance.cluster_name }}",
        node.data: "{{ elasticsearch_instance.is_data_node }}",
        node.master: "{{ elasticsearch_instance.is_master_node }}",
        http.cors.enabled : true,
        http.cors.allow-origin : "*",
        http.cors.allow-methods : "OPTIONS, HEAD, GET",
        http.cors.allow-headers : "X-Requested-With,X-Auth-Token,Content-Type, Content-Length",
        bootstrap.memory_lock: true,
        network.host: "{{ elasticsearch_instance.network_host }}",
        http.port: "{{ elasticsearch_instance.http_port }}",
        discovery.zen.ping.unicast.hosts: "{{ elasticsearch_instance.discovery_hosts | default('[\"127.0.0.1\", \"[::1]\"]') }}",
        transport.tcp.port: "{{ elasticsearch_instance.tcp_transport_port | default('9300') }}",
        discovery.zen.minimum_master_nodes: "{{ elasticsearch_instance.min_master_nodes | default('1') }}"
      }
