---

  - include_role:
      name: ansible-elasticsearch
    vars:
      es_instance_name: "{{ elasticsearch_instance.node_name }}"
      es_version: "5.6.9"
      es_major_version: "5.x"
      es_version_lock: true
      es_config: {
        node.name: "{{ elasticsearch_instance.node_name }}",
        cluster.name: "{{ elasticsearch_instance.cluster_name }}",
        node.data: "{{ elasticsearch_instance.is_data_node }}",
        node.master: "{{ elasticsearch_instance.is_master_node }}",
        http.cors.enabled : true,
        http.cors.allow-origin : "*",
        http.cors.allow-methods : "OPTIONS, HEAD, GET",
        http.cors.allow-headers : "X-Requested-With,X-Auth-Token,Content-Type, Content-Length",
        network.host: [_local_, _site_]
      }

  - include_role: name=refdata_indexer
