shared_folder_base_path: /metax
metax_app_base_path: "{{ shared_folder_base_path }}/{{ project_name }}"
project_repo_branch: master
default_user: ubuntu
django_user: metax-user
server_domain_name: metax.csc.local
server_certificate_name: nginx-selfsigned
