server_certificate_name: nginx-selfsigned
shared_folder_base_path: /metax
metax_app_base_path: "{{ shared_folder_base_path }}/{{ project_name }}"
project_repo_branch: staging
default_user: ubuntu
django_user: metax-user
server_domain_name: metax.csc.local
nginx_proxy_pass: http://127.0.0.1:8000

redis_sentinel_service: 'metax-master'
redis_sentinel_quorum: 2 # how many sentinels need to agree before switching master
redis_sentinel_listen_hosts: '127.0.0.1' # should be a list for other than local env

redis_instance_master_host: '127.0.0.1'
redis_instance_master_port: 6379
redis_instance_listen_hosts: '127.0.0.1' # should be a list for other than local env

# common values for all redis sentinels
redis_sentinel_common:
  redis_sentinel_quorum: "{{ redis_sentinel_quorum }}"
  redis_sentinel_service_name: "{{ redis_sentinel_service }}"
  redis_sentinel_listen_hosts: "{{ redis_sentinel_listen_hosts }}"
  redis_instance_master_host:  "{{ redis_instance_master_host }}"
  redis_instance_master_port:  "{{ redis_instance_master_port }}"

# redis_instance_1 is initially the master
redis_instance_1:
  redis_instance_number: 1
  redis_instance_port: "{{ redis_instance_master_port }}"
  redis_instance_listen_hosts: "{{ redis_instance_listen_hosts }}"

redis_instance_2:
  redis_instance_number: 2
  redis_instance_port: 6380
  redis_instance_listen_hosts: "{{ redis_instance_listen_hosts }}"

redis_sentinel_1:
  redis_sentinel_port: 5000
  redis_sentinel_number: 1
  common: "{{ redis_sentinel_common }}"

redis_sentinel_2:
  redis_sentinel_port: 5001
  redis_sentinel_number: 2
  common: "{{ redis_sentinel_common }}"

redis_sentinel_3:
  redis_sentinel_port: 5002
  redis_sentinel_number: 3
  common: "{{ redis_sentinel_common }}"
