server_certificate_name: metax-test
project_repo_branch: staging
default_user: cloud-user
django_user: metax-user
server_domain_name: 193.166.24.98
nginx_proxy_pass: http://unix:{{ metax_base_path }}/gunicorn/socket
