---


- name: Copy gunicorn config file
  template: src=templates/gunicorn_conf.py dest=/etc/gunicorn.py

- name: Create gunicorn logging directory
  file: path=/var/log/gunicorn state=directory owner={{ app_user }} group=metax

- name: Create gunicorn log files and ensure file permissions
  copy: content="" dest=/var/log/gunicorn/{{ item }}.log force=no owner={{ app_user }} group=metax mode=0755
  with_items:
    - gunicorn
    - gunicorn_error

- name: Create logrotate entry for gunicorn log file
  template: src=templates/logrotate_gunicorn dest=/etc/logrotate.d/gunicorn

- block:

    - name: Create {{ metax_base_path }}/gunicorn for Gunicorn socket and PID
      file: path={{ metax_base_path }}/gunicorn state=directory owner={{ app_user }} group=nginx mode=770

    - name: Copy gunicorn service file
      template: src=templates/gunicorn.service dest=/usr/lib/systemd/system/gunicorn.service

    - name: Copy gunicorn socket file
      template: src=templates/gunicorn.socket dest=/usr/lib/systemd/system/gunicorn.socket

    - name: Systemctl daemon-reload
      shell: "systemctl daemon-reload"

    - name: Restart gunicorn
      service: name=gunicorn state=restarted enabled=yes

  when: deployment_environment_id != 'local_development'
