---

- name: Create folder {{ metax_app_base_path }}
  file: path={{ metax_app_base_path }} state=directory owner=ubuntu group=ubuntu mode=0755

- name: Create folder {{ metax_db_data_path }}
  file: path={{ metax_db_data_path }} state=directory owner=ubuntu group=ubuntu mode=0755

- name: Ensure common packages
  apt: pkg={{ item }} state=latest
  with_items:
    - htop
    - git
    - zip
    - unzip
    - supervisor
    - curl
    - vim

- include: python.yml
