---

- name: Ensure os common packages
  apt: pkg={{ item }} state=latest update_cache=yes
  with_items:
    - htop
    - git
    - zip
    - unzip
    - curl
    - vim
    - aptitude

- name: Safe upgrade os packages
  apt:
    upgrade: safe
