---
  
- name: Create folder {{ metax_base_path }}
  file: path={{ metax_app_base_path }} state=directory owner=vagrant group=vagrant mode=0755

- name: Ensure common packages
  yum: pkg={{ item }} state=latest
  with_items:
    - yum-utils
    - htop
    - git
    - zip
    - unzip
    - supervisor
    - curl
    - libxslt-devel
    - libxml2-devel
    - vim

- include: python.yml
