---

- name: Make sure we have a 'wheel' group
  group: name=wheel state=present

- name: Allow 'wheel' group to have passwordless sudo
  lineinfile:
    dest: /etc/sudoers
    state: present
    regexp: '^%wheel'
    line: '%wheel ALL=(ALL) NOPASSWD: ALL'

- name: Make sure we have a 'metax' group in OS
  group: name=metax state=present

- name: Disable SSH password authentication
  lineinfile:
    dest: "/etc/ssh/sshd_config"
    regexp: "^PasswordAuthentication"
    line: "PasswordAuthentication no"
  when: deployment_environment_id != 'local_development'
  notify: restart sshd

- name: Install pip
  yum: name=python-pip state=latest
  when: deployment_environment_id != 'local_development'

- name: Update pip and install setuptools and pur
  pip: name={{ item }} state=latest
  with_items:
    - pip
    - setuptools
    - pur

- include_role: name=update_packages

- name: Ensure os common packages
  yum: name={{ item }} state=latest
  with_items:
    - '@Development tools'
    - python-devel
    - htop
    - git
    - zip
    - unzip
    - curl
    - vim
    - tcl
    - ntp
    - tree
    - zile
    - python-passlib
    - xqilla
    - xqilla-devel

- name: Disable SELinux (A better approach should be come up with!)
  selinux: state=permissive policy=targeted

# It seems at least in local dev centos 7 the fi_FI locale is already present!
# Make sure it is so also in other envs!
# - name: Install fi_FI locale
#   locale_gen:
#     name: fi_FI.UTF-8
#     state: present

- name: Set default locale as LC_ALL to fi_FI.UTF-8
  lineinfile:
    dest: /etc/environment
    state: present
    line: "LC_ALL=\"fi_FI.UTF-8\""

- name: Set default locale as LC_CTYPE to fi_FI.UTF-8
  lineinfile:
    dest: /etc/environment
    state: present
    line: "LC_CTYPE=\"fi_FI.UTF-8\""

- name: Set timezone to Europe/Helsinki
  timezone:
    name: Europe/Helsinki

- include_role: name=users

- name: Create /srv/metax base directory
  file: path=/srv/metax state=directory owner={{ django_user }} group=metax mode=0755

- block:

    - name: Copy bash aliases to {{ django_user }} user home dir
      template: src=templates/bash_aliases dest=/home/{{ django_user }}/.bash_aliases owner={{ django_user }} group={{ django_user }}

    - name: Touch .bash_profile
      file: path=/home/{{ django_user }}/.bash_profile owner={{ django_user }} group={{ django_user }} state=touch

    - name: Add printing of bash aliases to {{ django_user }} profile
      lineinfile:
        dest: "/home/{{ django_user }}/.bash_profile"
        state: present
        line: "{{ item }}"
      with_items:
        - "source .bash_aliases"
        - "aliases"

  when: deployment_environment_id in ['local_development', 'playground', 'test']
