---

- name: Make sure we have a 'metax' group in OS
  group: name=metax state=present

- name: Disable SSH password authentication
  lineinfile:
    dest: "/etc/ssh/sshd_config"
    regexp: "^PasswordAuthentication"
    line: "PasswordAuthentication no"
  when: deployment_environment_id != 'local_development'
  notify: restart sshd

- name: Install common yum packages
  yum:
    state: latest
    name:
      - gcc
      - gcc-c++
      - python-devel
      - git
      - curl
      - vim
      - zip
      - unzip
      - python-passlib
      - xqilla
      - xqilla-devel

- name: Install common os packages for development
  yum:
    state: latest
    name:
      - htop
      - tcl
      - ntp
      - tree
      - zile
  when: deployment_environment_id not in ['staging', 'production']

- name: Install pip using yum
  yum: name=python-pip state=latest
  when: deployment_environment_id != 'local_development'

- name: Install latest python pip and setuptools using pip
  pip:
    state: latest
    name:
      - pip
      - setuptools

- name: Install pur for updating pip dependencies using pip
  pip: name=pur state=latest
  when: deployment_environment_id == 'local_development'

- name: Reinstall glibc-common just in case to make Finnish locale available using yum
  shell: yum -y reinstall glibc-common
  args:
    warn: False
  when: deployment_environment_id == 'local_development'

- name: Disable SELinux
  selinux: state=permissive policy=targeted

- name: Set locale LANG to en_US.UTF-8
  shell: localectl set-locale LANG=en_US.UTF-8

- name: Set default locale as LC_ALL to fi_FI.UTF-8
  lineinfile:
    dest: /etc/environment
    state: present
    line: "LC_ALL=\"fi_FI.UTF-8\""

- name: Set default locale as LC_CTYPE to fi_FI.UTF-8
  lineinfile:
    dest: /etc/environment
    state: present
    line: "LC_CTYPE=\"fi_FI.UTF-8\""

- name: Set timezone to Europe/Helsinki
  timezone:
    name: Europe/Helsinki

- include_role: name=users

- name: Create app base directory {{ metax_base_path }}
  file: path={{ metax_base_path }} state=directory owner={{ app_user }} group=metax mode=0755

- block:
    - name: Copy bash aliases to {{ app_user }} user home dir
      template: src=templates/app_user_bash_aliases dest=/home/{{ app_user }}/.bash_aliases owner={{ app_user }} group={{ app_user }}

    - name: Touch {{ app_user }} .bash_profile
      file: path=/home/{{ app_user }}/.bash_profile owner={{ app_user }} group={{ app_user }} state=touch

    - name: Add printing of bash aliases to {{ app_user }} profile
      lineinfile:
        dest: "/home/{{ app_user }}/.bash_profile"
        state: present
        line: "{{ item }}"
      with_items:
        - "source .bash_aliases"
        - "aliases"

  when: deployment_environment_id in ['local_development', 'test', 'stable']

- include_role: name=update_packages
