---

# - name: Setup alternate SSH port
#   lineinfile:
#     dest: "/etc/ssh/sshd_config"
#     regexp: "^Port"
#     line: "Port 2222"
#   when: deployment_environment_id != 'local_development'
#   notify: "restart sshd"

- name: Disable SSH password authentication
  lineinfile:
    dest: "/etc/ssh/sshd_config"
    regexp: "^PasswordAuthentication"
    line: "PasswordAuthentication no"
  when: deployment_environment_id != 'local_development'
  notify: "restart sshd"

- include_role:
    name: update_packages
    
- name: Ensure os common packages
  apt: pkg={{ item }} state=latest
  with_items:
    - htop
    - git
    - zip
    - unzip
    - curl
    - vim
    - aptitude
