---

# - name: Setup alternate SSH port
#   lineinfile:
#     dest: "/etc/ssh/sshd_config"
#     regexp: "^Port"
#     line: "Port 2222"
#   when: deployment_environment_id != 'local_development'
#   notify: restart sshd

- name: Make sure we have a 'wheel' group
  group: name=wheel state=present

- name: Allow 'wheel' group to have passwordless sudo
  lineinfile:
    dest: /etc/sudoers
    state: present
    regexp: '^%wheel'
    line: '%wheel ALL=(ALL) NOPASSWD: ALL'

- name: Make sure we have a 'metax' group in OS
  group: name=metax state=present

- name: Create /srv/metax base directory
  file: path=/srv/metax state=directory owner={{ default_user }} group=metax mode=0755

- name: Disable SSH password authentication
  lineinfile:
    dest: "/etc/ssh/sshd_config"
    regexp: "^PasswordAuthentication"
    line: "PasswordAuthentication no"
  when: deployment_environment_id != 'local_development'
  notify: restart sshd

- name: Install aptitude
  apt: pkg=aptitude state=latest

- include_role: name=update_packages

- name: Ensure os common packages
  apt: pkg={{ item }} state=latest
  with_items:
    - build-essential
    - python-dev
    - python3-dev
    - htop
    - git
    - zip
    - unzip
    - curl
    - vim
    - tcl
    - ntp
    - tree
    - zile

- name: Install fi_FI local_development
  locale_gen:
    name: fi_FI.UTF-8
    state: present

- name: Set timezone to Europe/Helsinki
  timezone:
    name: Europe/Helsinki

- include_role: name=users
