- name: Install pip and virtualenv
  apt: name={{ item }} state=latest
  with_items:
    - python3-pip
    - python3-venv

- name: Setup virtual environment for Python to {{ python_virtualenv_path }}
  command: pyvenv {{ python_virtualenv_path }} creates={{ python_virtualenv_path }}

- name: Set owner of pyvenv to {{ django_user }} user
  file: path={{ python_virtualenv_path }} owner={{ django_user }} group=metax recurse=yes mode=0755

- name: install wheel package to enable using pip for installing requirements as {{ django_user }}
  pip: name=wheel virtualenv={{ python_virtualenv_path }}
  become_user: "{{ django_user }}"
