- name: Install virtualenv
  apt: name={{ item }} state=latest
  with_items:
    - python3-pip
    - python3-venv

- name: Install virtual environment for Python
  command: pyvenv {{ python_virtualenv_path }} creates={{ python_virtualenv_path }}
