- name: Install pip and virtualenv
  apt: name={{ item }} state=latest
  with_items:
    - python3-pip
    - python3-venv

- name: Setup virtual environment for Python to {{ python_virtualenv_path }}
  command: pyvenv {{ python_virtualenv_path }} creates={{ python_virtualenv_path }}

- name: Set owner of pyvenv to django user
  file: path={{ python_virtualenv_path }} owner={{ django_user }} group=metax recurse=yes

- name: install wheel package using pip (To enable using pip for installing requirements as {{ django_user }} in local dev env)
  pip: name=wheel virtualenv={{ python_virtualenv_path }}
  become: "{{ django_user }}"
  when: deployment_environment_id == 'local_development'
