---

- name: Clone/pull project repo
  git: repo={{ project_repo }} dest={{ metax_app_base_path }} accept_hostkey=yes
  notify:
  - restart gunicorn

- name: install python packages
  pip: requirements={{ metax_app_base_path }}/requirements.txt
  notify:
  - restart gunicorn

- name: copy nginx config
  template: src=metax_nginx.conf dest=/etc/nginx/sites-enabled/{{ project_name }}.conf
  notify:
  - restart nginx

- name: django migrate
  django_manage: command=migrate app_path={{ metax_app_base_path }} virtualenv={{ python_virtualenv_path }}

- name: django collectstatic
  django_manage: command=collectstatic app_path={{ metax_app_base_path }} virtualenv={{ python_virtualenv_path }}

- name: copy gunicorn config
  template: src=templates/gunicorn.j2 dest=/etc/init/gunicorn.conf
  notify:
  - restart gunicorn

- name: make sure nginx server is running
  service: name=nginx state=started enabled=yes

- name: make sure gunicorn server is running
  service: name=gunicorn state=started enabled=yes
