---

- name: NGINX | Install NGINX
  yum: name=nginx state=latest

- name: NGINX | Replace NGINX conf file
  template: src=templates/metax_nginx.conf dest=/etc/nginx/nginx.conf

- include_role: name=certificates

- name: NGINX | Generate Diffie-Hellman PFS (Perfect Forward Secrecy) group
  command: openssl dhparam -out {{ ssl_certificates_path }}/{{ nginx_dh_param_name }} 2048 creates={{ ssl_certificates_path }}/{{ nginx_dh_param_name }}

- name: NGINX | Create basic auth file
  htpasswd:
    path: /etc/nginx/nginx_auth
    name: "{{ item.username }}"
    password: "{{ item.password }}"
    owner: root
    group: nginx
    state: present
    mode: 0640
  with_items: "{{ nginx_credentials }}"

- name: NGINX | Restart NGINX
  service: name=nginx enabled=yes state=restarted
