# SPDX-FileCopyrightText: Copyright (c) 2018-2019 Ministry of Education and Culture, Finland
#
# SPDX-License-Identifier: GPL-3.0-or-later
---

- name: NGINX | Install NGINX
  yum: name=nginx state=latest

- name: NGINX | Replace NGINX conf file
  template: src=templates/metax_nginx.conf dest=/etc/nginx/nginx.conf

- name: NGINX | Copy shared_headers.conf
  template: src=templates/shared_headers.conf dest=/etc/nginx/shared_headers.conf

- name: NGINX | Copy api_response_headers.conf
  template: src=templates/api_response_headers.conf dest=/etc/nginx/api_response_headers.conf

- name: NGINX | Copy static_file_headers.conf
  template: src=templates/static_file_headers.conf dest=/etc/nginx/static_file_headers.conf

- name: NGINX | Copy elastic_headers.conf
  template: src=templates/elastic_headers.conf dest=/etc/nginx/elastic_headers.conf

- name: NGINX | Copy robots.txt
  template: src=templates/robots.txt dest=/etc/nginx/robots.txt
  when: deployment_environment_id not in ['production']

- include_role: name=certificates

- name: NGINX | Generate Diffie-Hellman PFS (Perfect Forward Secrecy) group
  command: openssl dhparam -out {{ ssl_certificates_path }}/{{ nginx_dh_param_name }} 2048 creates={{ ssl_certificates_path }}/{{ nginx_dh_param_name }}

- name: NGINX | Create basic auth file
  htpasswd:
    path: /etc/nginx/nginx_auth
    name: "{{ item.username }}"
    password: "{{ item.password }}"
    owner: root
    group: nginx
    state: present
    mode: 0640
  with_items: "{{ nginx_credentials }}"

- name: NGINX | Restart NGINX
  service: name=nginx enabled=yes state=restarted
