---

- name: NGINX | Install NGINX
  apt: pkg=nginx state=latest

- name: NGINX | Copy NGINX conf file to sites-available
  template: src=templates/metax_nginx.conf dest=/etc/nginx/sites-available/metax

- name: NGINX | Symlink NGINX conf file to sites-enabled
  file: state=link src=/etc/nginx/sites-available/metax dest=/etc/nginx/sites-enabled/metax

- name: NGINX | Remove default NGINX config file
  file: path=/etc/nginx/sites-enabled/default state=absent

- name: NGINX | Create directory for ssl certificates
  file: path=/etc/nginx/ssl_certs state=directory

- include_role: name=certificates

- name: NGINX | Generate Diffie-Hellman PFS (Perfect Forward Secrecy) group (this is going to take a while)
  command: openssl dhparam -out /etc/nginx/ssl_certs/dhparam.pem 2048 creates=/etc/nginx/ssl_certs/dhparam.pem

- name: NGINX | Create basic auth file for elasticsearch
  htpasswd:
    path: /etc/nginx/es_auth
    name: "{{ item.username }}"
    password: "{{ item.password }}"
    owner: root
    group: www-data
    state: present
    mode: 0640
  with_items: "{{ es_users }}"

- name: NGINX | Restart NGINX
  service: name=nginx enabled=yes state=restarted
