---

- name: NGINX | Install NGINX
  apt: pkg=nginx state=latest

- name: NGINX | Configure NGINX
  copy: src=vars/metax_nginx.conf dest=/etc/nginx/

- name: NGINX | Start NGINX
  service: name=nginx enabled=yes state=started
