---

- include_role: name=update_packages

- name: Get current timestamp
  shell: date +%Y%m%d%H%M%S
  register: timestamp

- name: Backup database
  shell: "pg_dump --format=custom $METAX_DATABASE_NAME -f {{ metax_db_backup_archive_path }}/metax_db_{{ deployment_environment_id }}_backup_{{ timestamp.stdout }}.dump"
  args:
    executable: /bin/bash
  become_user: postgres

- block:
    - name: Drop current metax database
      shell: "psql -c 'DROP DATABASE '\"$METAX_DATABASE_NAME\"';'"
      args:
        executable: /bin/bash

    - name: Recreate metax database
      shell: "psql -c 'CREATE DATABASE '\"$METAX_DATABASE_NAME\"' WITH OWNER='\"$METAX_DATABASE_USER\"' TEMPLATE=template0 ENCODING=\"'\"UTF8\"'\" LC_COLLATE=\"'\"fi_FI.UTF-8\"'\" LC_CTYPE=\"'\"fi_FI.UTF-8\"'\";'"
      args:
        executable: /bin/bash

  become_user: postgres
  when: deployment_environment_id in ['local_development', 'playground', 'test']
