---

- include_role: name=update_packages

- name: Find database backups older than 10 days
  command: "find {{ metax_db_backup_archive_path }} -type f -mtime +10"
  register: archived_backups

- name: Get current timestamp
  shell: date +%Y%m%d%H%M%S
  register: timestamp

- block:
    - name: Delete the old database backups
      file: state=absent path={{ item }}
      with_items: "{{ archived_backups.stdout_lines }}"

    - name: Backup database
      shell: "pg_dump $METAX_DATABASE_NAME -f {{ metax_db_backup_archive_path }}/metax_db_{{ deployment_environment_id }}_backup_{{ timestamp.stdout }}.dump"
      args:
        executable: /bin/bash

  become_user: postgres

# - name: Check if a reboot is required
#   shell: "[ -f /var/run/reboot-required ]"
#   failed_when: False
#   register: reboot_required
#   changed_when: reboot_required.rc == 0
#   notify: reboot
#   when: deployment_environment_id != 'local_development' and deployment_environment_id != 'playground'
