---

- include_role:
    name: update_packages

- name: Create db backup directories
  file: owner=postgres group=postgres mode=0750 state=directory path={{ item }}
  with_items:
    - "{{ metax_db_backup_path }}"
    - "{{ metax_db_backup_path }}/latest"
    - "{{ metax_db_backup_path }}/archive"

- name: Find latest backup
  command: "find {{ metax_db_backup_path }}/latest -type f"
  register: latest_backup

- name: Find archived backups
  command: "find {{ metax_db_backup_path }}/archive -type f -mtime +5"
  register: archived_backups

- name: Get current timestamp
  shell: date +%Y%m%d%H%M%S
  register: timestamp

- block:
    - name: Delete old db backups
      file: state=absent path={{ item }}
      with_items: "{{ archived_backups.stdout_lines }}"

    - name: Move previous db backup to archive
      command: mv {{ item }} {{ metax_db_backup_path }}/archive
      with_items: "{{ latest_backup.stdout_lines }}"

    # Backing up of the database should be done so that the backups go to some more permanent location than the local machine
    - name: Source global env vars and backup database
      shell: "{{ item }}"
      args:
        executable: /bin/bash
      with_items:
        - source /etc/environment
        - pg_dump -f {{ metax_db_backup_path }}/latest/metax_db_{{ deployment_environment_id }}_backup_{{ timestamp.stdout }}.dump

  become_user: postgres

# - name: Check if a reboot is required
#   shell: "[ -f /var/run/reboot-required ]"
#   failed_when: False
#   register: reboot_required
#   changed_when: reboot_required.rc == 0
#   notify: reboot
#   when: deployment_environment_id != 'local_development' and deployment_environment_id != 'playground'
