---

- include_role: name=update_packages

- name: Get current timestamp
  shell: date +%Y%m%d%H%M%S
  register: timestamp

- name: Backup database
  shell: "pg_dump --format=custom $METAX_DATABASE_NAME -f {{ metax_db_backup_archive_path }}/metax_db_{{ deployment_environment_id }}_backup_{{ timestamp.stdout }}.dump"
  args:
    executable: /bin/bash
  become_user: postgres

- block:
  - name: Drop current metax database
    postgresql_db: db={{ metax_database }} state=absent

  - name: Recreate metax database
    postgresql_db: template=template0 db={{ metax_database }} owner={{ metax_database_user }} state=present encoding=UTF-8 lc_collate=fi_FI.UTF-8 lc_ctype=fi_FI.UTF-8

  become_user: postgres
  when: deployment_environment_id in ['local_development', 'playground', 'staging']

# - name: Check if a reboot is required
#   shell: "[ -f /var/run/reboot-required ]"
#   failed_when: False
#   register: reboot_required
#   changed_when: reboot_required.rc == 0
#   notify: reboot
#   when: deployment_environment_id != 'local_development' and deployment_environment_id != 'playground'
