---

- hosts: webservers
  vars:
    is_provision: false
  become: yes
  vars_files:
    - "inventories/common_vars.yml"
  roles:
    - deploy_webservers
    - { role: reboot,
        when: deployment_environment_id != 'local_development' and deployment_environment_id != 'playground'
      }
