---

- hosts: dbservers
  vars:
    is_provision: false
  become: yes
  vars_files:
    - "vars/common.yml"
    - "vars/environments/{{ deployment_environment_id }}.yml"
  roles:
    - deploy_dbservers
    - { role: reboot,
        when: deployment_environment_id != 'local_development' and deployment_environment_id != 'playground'
      }
