# SPDX-FileCopyrightText: Copyright (c) 2018-2019 Ministry of Education and Culture, Finland
#
# SPDX-License-Identifier: GPL-3.0-or-later
---

- hosts: webservers
  become: yes
  roles:
    - deploy_webservers
    - docs
    - { role: reboot, when: "deployment_environment_id not in ['local_development', 'staging', 'production']" }
