---

- hosts: dbservers
  vars:
    is_provision: false
  become: yes
  roles:
    - deploy_dbservers
    - { role: reboot, when: deployment_environment_id != 'local_development' and deployment_environment_id != 'playground' }
