---

- hosts: dbservers
  vars:
    is_provision: false
  become: yes
  roles:
    - update_packages
    - deploy_dbservers
    - { role: reboot, when: deployment_environment_id not in ['local_development', 'playground', 'staging', 'production']}
