---

- hosts: webservers
  vars:
    is_provision: false
  become: yes
  vars_files:
    - "vars/common.yml"
    - "vars/environments/{{ deployment_environment_id }}.yml"
    - "sec/vars/{{ deployment_environment_id }}.yml"
  roles:
    - deploy_webservers
  handlers:
    - name: restart nginx
      service: name=nginx state=restarted
    - name: reboot
      command: /sbin/reboot
