---

- hosts: dbservers
  become: yes
  vars_files:
    - "vars/common.yml"
    - "vars/environments/{{ deployment_environment_id }}.yml"
    - "sec/vars/{{ deployment_environment_id }}.yml"
  roles:
    - deploy_dbservers
  handlers:
    - name: reboot
      command: /sbin/reboot
