---

- hosts: webservers
  become: yes
  roles:
    - { role: os-base, when: "deployment_environment_id not in ['local_development', 'playground']" }
    - { role: update_packages, when: "deployment_environment_id not in ['local_development', 'playground']" }
    - python
    - redis
    - nginx
    #- rabbitmq TODO: Uncomment this when rabbitmq cluster is to be created
    - provision_app
  handlers:
    - name: restart sshd
      service: name=sshd state=restarted
