---

- hosts: dbservers
  vars:
    is_provision: true
  become: yes
  vars_files:
    - "inventories/common_vars.yml"
  pre_tasks:
    - name: Place database name into target VM env vars
      lineinfile:
        dest: /etc/environment
        state: present
        line: 'METAX_DATABASE_NAME="{{ metax_database }}"'
    - name: Place database user into target VM env vars
      lineinfile:
        dest: /etc/environment
        state: present
        line: 'METAX_DATABASE_USER="{{ metax_database_user }}"'
  roles:
    - os-base
    - postgres
    - backup
  handlers:
    - name: restart sshd
      service: name=sshd state=restarted
