---

- hosts: dbservers
  vars:
    is_provision: true
  become: yes
  vars_files:
    - "vars/common.yml"
    - "vars/environments/{{ deployment_environment_id }}.yml"
    - "sec/vars/{{ deployment_environment_id }}.yml"
    - "sec/vars/dbservers.yml"
  pre_tasks:
    - name: Place database name into target VM env vars
      lineinfile:
        dest: /etc/environment
        state: present
        line: 'METAX_DATABASE_NAME="{{ metax_database }}"'
    - name: Place database user into target VM env vars
      lineinfile:
        dest: /etc/environment
        state: present
        line: 'METAX_DATABASE_USER="{{ metax_database_user }}"'
  roles:
    - os-base
    - postgres
    - backup
  handlers:
    - name: restart sshd
      service: name=sshd state=restarted
