---

- hosts: master-messageservers
  become: yes
  roles:
    - { role: os-base, when: "deployment_environment_id != 'local_development'" }
    - rabbitmq

- hosts: slave-messageservers
  become: yes
  roles:
    - { role: os-base, when: "deployment_environment_id != 'local_development'" }
    - { role: rabbitmq, when: "deployment_environment_id != 'local_development'" }
