---

- hosts: webservers
  become: yes
  roles:
    - { role: os-base, when: "deployment_environment_id not in ['local_development', 'playground']" }
    - { role: python, when: "deployment_environment_id not in ['local_development', 'playground']" }
    - nginx
    - apache
    - provision_app
