---

- hosts: webservers
  become: yes
  vars_files:
    - "vars/common.yml"
    - "vars/environments/{{ deployment_environment_id }}.yml"
    - "vars/environments/{{ deployment_environment_id }}_sec.yml"
  pre_tasks:
    - name: Copy app config to target VM
      copy: src=vars/environments/{{ deployment_environment_id }}_sec.yml dest=/home/{{ django_user }}/app_config owner={{ django_user }} group=metax mode=0440
  roles:
    - os-base
    - python
    - nginx
    - redis
    - rabbitmq
    - provision_django
  handlers:
    - name: restart sshd
      service: name=sshd state=restarted
