---

- hosts: webservers
  become: yes
  vars_files:
    - "vars/common.yml"
    - "vars/environments/{{ deployment_environment_id }}.yml"
    - "sec/vars/{{ deployment_environment_id }}.yml"
    - "sec/vars/webservers.yml"
  roles:
    - os-base
    - python
    - nginx
    - redis
    - provision_django
  handlers:
    - name: restart sshd
      service: name=sshd state=restarted
