---

- hosts: webservers
  vars:
    is_provision: true
  become: yes
  vars_files:
    - "inventories/common_vars.yml"
  roles:
    - os-base
    - python
    - nginx
    - redis
    - provision_django
  handlers:
    - name: restart sshd
      service: name=sshd state=restarted
