---

- hosts: dataservers
  vars:
    is_provision: true
  become: yes
  vars_files:
    - "inventories/common_vars.yml"
  roles:
    - os-base
    - python
    - rabbitmq
    - elasticsearch
  handlers:
    - name: restart sshd
      service: name=sshd state=restarted
