---

- hosts: dataservers
  vars:
    is_provision: true
  become: yes
  roles:
    - { role: os-base, when: deployment_environment_id != 'local_development' and deployment_environment_id != 'playground' }
    - { role: python, when: deployment_environment_id != 'local_development' and deployment_environment_id != 'playground' }
    - rabbitmq
    - elasticsearch
  handlers:
    - name: restart sshd
      service: name=sshd state=restarted
