---

- hosts: cacheservers
  vars:
    is_provision: true
  become: yes
  roles:
    - { role: os-base, when: "deployment_environment_id not in ['local_development', 'playground']" }
    - { role: update_packages, when: "deployment_environment_id not in ['local_development', 'playground']" }
    - python
    - redis
  handlers:
    - name: restart sshd
      service: name=sshd state=restarted
