---

- hosts: dbservers
  become: yes
  vars_files:
    - "vars/common.yml"
    - "vars/environments/{{ deployment_environment_id }}.yml"
    - "vars/environments/{{ deployment_environment_id }}_sec.yml"
  pre_tasks:
    - name: Place database name into target VM env vars
      lineinfile:
        dest: /etc/environment
        state: present
        line: 'PGDATABASE="{{ metax_database }}"'
  roles:
    - os-base
    - postgres
    - { role: backup, when: deployment_environment_id != 'local_development' }
  handlers:
    - name: restart sshd
      service: name=sshd state=restarted
    - name: restart postgres
      service: name=postgresql state=restarted
