---

- hosts: webservers
  become: yes
  roles:
    - { role: os-base, when: "deployment_environment_id != 'local_development'" }
    - { role: python, when: "deployment_environment_id != 'local_development'" }
    - nginx
    - apache
    - provision_app
    - docs
