---

- hosts: dataservers
  vars:
    is_provision: true
  become: yes
  vars_files:
    - "vars/common.yml"
    - "vars/environments/{{ deployment_environment_id }}.yml"
    - "sec/vars/{{ deployment_environment_id }}.yml"
    - "sec/vars/dataservers.yml"
  roles:
    - os-base
    - python
    - rabbitmq
    - elasticsearch
