---

- hosts: dbservers
  become: yes
  roles:
    - os-base
    - update_packages
    - postgres
    - backup
    #- rabbitmq TODO: Uncomment this when rabbitmq cluster is to be created
    #- elasticsearch TODO: Uncomment this when es cluster is to be created
  handlers:
    - name: restart sshd
      service: name=sshd state=restarted
