# SPDX-FileCopyrightText: Copyright (c) 2018-2019 Ministry of Education and Culture, Finland
#
# SPDX-License-Identifier: GPL-3.0-or-later
---

- src: https://github.com/CSCfi/ansible-elasticsearch
  version: 251053c04e2cd80aa90df6146ad5b4209c86bbd7
