---

- hosts: local_development
  become: yes
  vars_files:
    - "vars/common.yml"
    - "vars/environments/{{ deployment_environment_id }}.yml"
    - "{{ secrets_file_path }}"
  roles:
    - os-base
- include: provision_dbservers.yml
- include: provision_webservers.yml
- include: deploy.yml
