# SPDX-FileCopyrightText: Copyright (c) 2018-2019 Ministry of Education and Culture, Finland
#
# SPDX-License-Identifier: GPL-3.0-or-later
---

- hosts: distincthosts
  become: yes
  roles:
    - { role: update_packages, when: "deployment_environment_id not in ['production']" }
