# SPDX-FileCopyrightText: Copyright (c) 2018-2019 Ministry of Education and Culture, Finland
#
# SPDX-License-Identifier: GPL-3.0-or-later
---

- hosts: refdataservers
  become: yes
  roles:
    - refdata
  vars:
    task: indexer

- hosts: webservers
  become: yes
  tasks:
    - name: Restart gunicorn
      service:
        name: gunicorn
        state: restarted
      when: deployment_environment_id != 'local_development'
